"""numero

Revision ID: 3e4bfeda1dbd
Revises: 4698bd7f8533
Create Date: 2015-03-01 17:22:33.417166

"""

# revision identifiers, used by Alembic.
revision = '3e4bfeda1dbd'
down_revision = '4698bd7f8533'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocolo', sa.Column('numero', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocolo', 'numero')
    ### end Alembic commands ###
