"""inicial

Revision ID: 4568153f9481
Revises: None
Create Date: 2015-02-11 22:10:28.081439

"""

# revision identifiers, used by Alembic.
revision = '4568153f9481'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_protocolo', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocolo')
    ### end Alembic commands ###
