"""Adiciona tabela role

Revision ID: 46848d037f26
Revises: 2bf79a677f9d
Create Date: 2015-02-28 16:57:46.682666

"""

# revision identifiers, used by Alembic.
revision = '46848d037f26'
down_revision = '2bf79a677f9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.add_column(u'user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'role_id')
    op.drop_table('role')
    ### end Alembic commands ###
