"""endereco

Revision ID: 4698bd7f8533
Revises: 46848d037f26
Create Date: 2015-03-01 17:01:47.860500

"""

# revision identifiers, used by Alembic.
revision = '4698bd7f8533'
down_revision = '46848d037f26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocolo', sa.Column('bairro', sa.Text(), nullable=True))
    op.add_column('protocolo', sa.Column('cep', sa.String(length=255), nullable=True))
    op.add_column('protocolo', sa.Column('cidade', sa.Text(), nullable=True))
    op.add_column('protocolo', sa.Column('rua', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocolo', 'rua')
    op.drop_column('protocolo', 'cidade')
    op.drop_column('protocolo', 'cep')
    op.drop_column('protocolo', 'bairro')
    ### end Alembic commands ###
