"""logradouro e estado

Revision ID: 531b73bb0e7e
Revises: 3e4bfeda1dbd
Create Date: 2015-03-01 18:00:21.928624

"""

# revision identifiers, used by Alembic.
revision = '531b73bb0e7e'
down_revision = '3e4bfeda1dbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocolo', sa.Column('estado', sa.String(length=2), nullable=True))
    op.add_column('protocolo', sa.Column('logradouro', sa.Text(), nullable=True))
    op.drop_column('protocolo', 'rua')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocolo', sa.Column('rua', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('protocolo', 'logradouro')
    op.drop_column('protocolo', 'estado')
    ### end Alembic commands ###
