"""user

Revision ID: 2bf79a677f9d
Revises: 420a26e3a847
Create Date: 2015-02-28 13:22:50.256479

"""

# revision identifiers, used by Alembic.
revision = '2bf79a677f9d'
down_revision = '420a26e3a847'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
