"""nome_email

Revision ID: 447aa780ca24
Revises: 531b73bb0e7e
Create Date: 2015-05-03 12:39:20.512298

"""

# revision identifiers, used by Alembic.
revision = '447aa780ca24'
down_revision = '531b73bb0e7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocolo', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('protocolo', sa.Column('nome', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protocolo', 'nome')
    op.drop_column('protocolo', 'email')
    ### end Alembic commands ###
